# Generated by Django 5.2.12 on 2026-04-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='all_probs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='risk_category',
            field=models.CharField(default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
